#!/bin/bash
regex="^(refs)[\ ]\#[0-9]+\:[\ ]((EXT|EE|EG)\-)[0-9]+[\ ]\-[\ ]"
var=`head -n 1 $1`

function info {
  echo >&2 $1
}

function debug {
  debug=false
  if $debug
  then
    echo >&2 $1
  fi
}

if [[ "$var" =~ $regex ]]
then
  debug "Commit message OK"
else
  # Print information about acceptable format for commit message
  info "Commit message must be in the form \"refs #[_ID_REDMINE_]: [EXT|EE|EG]-[_ID_USER_STORY_] - message\""
  info "If 'EXT-_ID_USER_STORY_' is not available just use 'EXT-000'"
  exit 1
fi
